### ISSUE TITLE
[JSON-RPC] Access map. Ability to set roles for namespaces.

### ISSUE THREAD

**Issue by Kilte** [vermillion-php/vermillion#4]
Before:

```yaml
// jsonrpc.yml
access_map:
  manage.quests: ROLE_ADMIN
  manage.get.quest: ROLE_ADMIN
  manage.save.quest: ROLE_ADMIN
  manage.get.screens: ROLE_ADMIN
  quest.screen.current: ROLE_USER
  quest.screen.next: ROLE_USER
  quest.restart: ROLE_USER
  user.listing: ROLE_ADMIN
exception:
  access_denied: -32001
```
After:
```yaml
// jsonrpc.yml
access_map:
  manage.*: ROLE_ADMIN
  quest.*: ROLE_USER  
  user.listing: ROLE_ADMIN
exception:
  access_denied: -32001
```
